version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_ENVIRONMENT=prod
      - DATABASE_JDBC_URL=jdbc:postgresql://db:5432/ozgurclub
      - DATABASE_USER=ozgurclub
      - DATABASE_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ozgurclub
      - POSTGRES_USER=ozgurclub
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 