services:
  web:
    build: .
    ports:
      - "8182:8080"
    develop:
      watch:
        - path: .
          action: rebuild
    environment:
      APP_ENVIRONMENT: production
      DATABASE_JDBC_URL: jdbc:postgresql://db:5432/postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: p.postgres
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: p.postgres
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s